### ISSUE TITLE
The plugin for Nuxt 3 seems to slower than the plugin for Nuxt 2

### ISSUE THREAD

**Issue by hlassiege** [nuxt-modules/prismic#174] opened 2022-12-05 13:01 UTC
### Versions

- nuxt: 3.0.0
- @nuxtjs/prismic: 3.0.0-rc.2
- node: 16.17

### Reproduction

Both projects are here : 

https://gitlab.com/maltcommunity/public/singapore-prototypes/-/tree/master/prismic-nuxt-2
https://gitlab.com/maltcommunity/public/singapore-prototypes/-/blob/master/prismic-nuxt-3

### Steps to reproduce

We encountered performance issues since our migration to Nuxt3 and we suspect the prismic module.

When running the projects above, we log the time on both version to query a prismic document

To reproduce, just checkout the projects, run npm install and then npm dev

### What is Expected?

Time should be equivalent in both version

### What is actually happening?

Time are quite different 
![image](https://user-images.githubusercontent.com/666123/205643430-1420b1a5-a2df-4e3d-88cb-3463e4976505.png)

With nuxt3, the time is significatively slower

**Comment by hlassiege** [comment] 2022-12-05 13:02
I'm not sure this is related to nuxt so I'll post an issue on prismic client also

**Comment by lihbr** [comment] 2022-12-05 18:31
Hey there, thanks for opening an issue, and thank you so much for the comprehensive reproduction, I was able to reproduce it!

Indeed, with this setup, it appears that `@prismicio/client` version 5 is \**faster*\* than `@prismicio/client` version 7. However, when turning on the [`modern` option on Nuxt 2 module](https://prismic.nuxtjs.org/configuration#modern), we now see comparable results:

![image](https://user-images.githubusercontent.com/25330882/205712691-48561a03-abbb-48c3-b248-ea7e6cf582fd.png)

***So why the `modern` option on Nuxt 2?***

When not using this option, `@prismicio/client` version 5 gets inited using an old, deprecated, and not feature-full method that can cause issues with previews namely. The `modern` option initializes the client in a more modern way/feature-full way.

With all of that in mind, maybe you can try running your Nuxt 2 application with the `modern` option turned on so that you can maybe confirm if Prismic is indeed your performance bottleneck?
While biased, I think 100ms is a decent API response time that shouldn't represent a bottleneck in such application(?)

**Comment by hlassiege** [comment] 2022-12-05 18:43
Our current application is using nuxt 3, not nuxt 2 and I'm not looking for the same performance penalty :) I'd like on the contrary the have the performance I used to have in the previous app. 

In this example, it vary within the range 100/200ms. But on real use case with more complex slices the variation is more in the range 500/900ms. With our old version, it was in the range 30/70ms. The difference is quite huge

I don't seen the parameter "modern" in the nuxt 3 plugin https://v3.prismic.nuxtjs.org/configuration
Do you confirm it does not exist anymore ?

**Comment by lihbr** [comment] 2022-12-05 19:59
> Our current application is using nuxt 3, not nuxt 2 and I'm not looking for the same performance penalty :) I'd like on the contrary the have the performance I used to have in the previous app.

Yes, my suggestion was to confirm that turning on `modern` in the old application resulted in the same performance issues that you experience in the new application.

> In this example, it vary within the range 100/200ms. But on real use case with more complex slices the variation is more in the range 500/900ms. With our old version, it was in the range 30/70ms. The difference is quite huge.

Interesting, are you able to provide a more performance-heavy call example (just the query, I can update it manually in the reproduction). It might help exacerbate the less-performant part of the code for further troubleshooting.

> I don't seen the parameter "modern" in the nuxt 3 plugin [v3.prismic.nuxtjs.org/configuration](https://v3.prismic.nuxtjs.org/configuration)

Indeed, the `modern` option is for Nuxt 2 only (the Nuxt 3 module is only "modern" so to say, not legacy)

**Comment by hlassiege** [comment] 2022-12-06 10:12
To summarize.
Here is the result with the original setup in the repository 

Nuxt 3
![image](https://user-images.githubusercontent.com/666123/205880463-c5e83c23-b6b6-4d3a-8648-11a65cbd23b0.png)

Nuxt 2 
![image](https://user-images.githubusercontent.com/666123/205880523-426cda26-7993-4f45-a7c8-4d9b064da9ba.png)

It's approximatively 334% of performance degradation.

With Nuxt 2 and modern option activated, indeed we have the same degradation : 

![image](https://user-images.githubusercontent.com/666123/205881184-657f628a-06eb-49c3-b501-9288280af809.png)

In "real" conditions within our application the performance of prismic is quite different as you can see in this flamegraph : 

![image](https://user-images.githubusercontent.com/666123/205882461-284d1644-65fb-4b78-ac3f-dc416badcdd1.png)

I don't know exactly how to isolate the problem in the public repository because I still don't know what's causing this. 
In the flamegraph (made with datadog) there is not details in the green line about prismic

**Comment by hlassiege** [comment] 2022-12-06 13:09
We will try to create the same flamegraph on the old application

Currently, I can only time the whole response time from the server 
With nuxt 3 
![image](https://user-images.githubusercontent.com/666123/205917215-aab6bc4d-fae8-4e88-81ae-f803933ba9d1.png)

With nuxt 2
![image](https://user-images.githubusercontent.com/666123/205920632-1edf4802-b692-481e-bece-77da11007963.png)

The time is, in average, 2x slower. 

The website content is exactly the same, slices are identicals. 

Calls to prismic are already parallelize as we can see in this flamegraphs, they don't sum up 
![image](https://user-images.githubusercontent.com/666123/205920882-74c6df22-047e-4a82-af46-9b0f3013278e.png)

We continue to investigate

**Comment by lihbr** [comment] 2022-12-06 14:30
OK, thanks again for sharing the details! Let me know if you happen to find anything else.

I'll check internally on our end if we can find anything tied to your specific project.

**Comment by hlassiege** [comment] 2022-12-07 09:19
Hi,

For previews, we still use the standard client. We may use [webhooks ](https://prismic.io/docs/webhooks) to evict the cache.

About the API, yes I really don't know why I have those differences in both versions. You're right, it's the same API, the same content. It's really weird and I don't understand.
Even if, maybe we would have had the same performance in our previous app with modern:true. We tested that on the small project but we didn't tried on the old app. I'll test it today.

**Comment by lihbr** [comment] 2023-03-07 13:04
Closing this one as I think it has been overall answered

_tl;dr; client seems to be working as expected when it comes to timing between Nuxt 2 and Nuxt 3 versions, or it is an upstream issue._

**Closed by lihbr** 2023-03-07 13:04 UTC
Labels: bug, question

**Comment by OlgaLookina** [comment] 2024-04-01 16:25
@hlassiege Hi! We also encountered the same problem. Did you find another solution?

**Comment by hlassiege** [comment] 2024-04-01 16:50
@OlgaLookina we had to create a proxy to cache the answer from prismic. 
We never found a good builtin solution with prismic itself.
